# Generated by Django 4.0.4 on 2022-06-07 19:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('click_power', models.IntegerField(default=1)),
                ('level', models.IntegerField(default=0)),
                ('tentacle1_count', models.IntegerField(default=0)),
                ('tentacle2_count', models.IntegerField(default=0)),
                ('tentacle3_count', models.IntegerField(default=0)),
                ('tentacle4_count', models.IntegerField(default=0)),
                ('tentacle5_count', models.IntegerField(default=0)),
                ('tentacle1_cost', models.IntegerField(default=10)),
                ('tentacle2_cost', models.IntegerField(default=50)),
                ('tentacle3_cost', models.IntegerField(default=250)),
                ('tentacle4_cost', models.IntegerField(default=1250)),
                ('tentacle5_cost', models.IntegerField(default=6250)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
