# Generated by Django 4.1.4 on 2023-01-07 11:50

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('click_power', models.IntegerField(default=1)),
                ('level', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
            managers=[
                ('tentacles', django.db.models.manager.Manager()),
            ],
        ),
    ]
