# Generated by Django 4.1.4 on 2022-12-14 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clicker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='click_power',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
