# Generated by Django 4.0.4 on 2022-05-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clicker', '0003_userdata_level_boostdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='level',
            new_name='tentacle1_count',
        ),
        migrations.AddField(
            model_name='userdata',
            name='tentacle2_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='tentacle3_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='tentacle4_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userdata',
            name='tentacle5_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='BoostData',
        ),
    ]
