# Generated by Django 4.1.4 on 2022-12-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clicker', '0003_rename_userinfo_results_alter_results_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tentacles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost', models.IntegerField(default=0)),
                ('power', models.IntegerField(default=1)),
            ],
        ),
    ]
