# Generated by Django 4.1.4 on 2022-12-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clicker', '0004_tentacles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tentacles',
            options={'verbose_name': 'Тентакли', 'verbose_name_plural': 'Тентакли'},
        ),
        migrations.AddField(
            model_name='tentacles',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tentacles_images'),
        ),
    ]
