# Generated by Django 4.0.4 on 2022-06-07 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clicker', '0005_tentacles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tentacles',
        ),
    ]
